import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
import {Network} from './network.js';

export class NexstrikeGame{
 constructor(root,ui){this.root=root;this.ui=ui;this.net=new Network();this.clock=new THREE.Clock();this.keys={};this.enemies=[];this.remote=new Map();this.hp=100;this.ammo=25;this.weapon='NX-9';this.yaw=0;this.pitch=0;this.lock=false;this.init();this.bind();this.net.connect(ui.name());}
 init(){this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0x080c15);this.scene.fog=new THREE.Fog(0x080c15,35,150);this.camera=new THREE.PerspectiveCamera(76,innerWidth/innerHeight,.05,300);this.camera.position.set(0,1.7,16);this.renderer=new THREE.WebGLRenderer({antialias:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.setSize(innerWidth,innerHeight);this.renderer.shadowMap.enabled=true;this.root.append(this.renderer.domElement);this.scene.add(new THREE.HemisphereLight(0xb7c8ff,0x18202d,1.7));let sun=new THREE.DirectionalLight(0xffffff,2.3);sun.position.set(20,40,10);sun.castShadow=true;this.scene.add(sun);this.buildMap();this.buildWeapon();this.spawnBots();this.netEvents();this.loop()}
 mat(c,m=0.7){return new THREE.MeshStandardMaterial({color:c,metalness:.25,roughness:m})}
 box(x,y,z,c=0x202938){let o=new THREE.Mesh(new THREE.BoxGeometry(x,y,z),this.mat(c));o.castShadow=o.receiveShadow=true;this.scene.add(o);return o}
 buildMap(){let floor=this.box(110,.2,110,0x101722);floor.position.y=-.1;for(let i=-5;i<=5;i++){let wall=this.box(1,4,22,0x273246);wall.position.set(i*9,2,(i%2?0:-18));}for(let z=-45;z<=45;z+=9){let w=this.box(38,4,1,0x222d3e);w.position.set(0,2,z);}for(const [x,z] of [[-28,-20],[-15,-5],[18,-12],[30,8],[-30,20],[12,28]]){let c=this.box(5,2.2,4,0x334057);c.position.set(x,1.1,z)}this.site(-30,-28,'A');this.site(0,0,'B');this.site(30,25,'C');}
 site(x,z,t){let p=this.box(15,.08,15,0x242d3c);p.position.set(x,.02,z);for(let i=-1;i<2;i++){let line=this.box(.06,.04,14,0x756cff);line.position.set(x+i*5,.08,z)}let geo=new THREE.RingGeometry(1.5,1.7,32);let r=new THREE.Mesh(geo,this.mat(0x8b7cff));r.rotation.x=-Math.PI/2;r.position.set(x,.1,z);this.scene.add(r);}
 buildWeapon(){let g=new THREE.Group();let body=new THREE.Mesh(new THREE.BoxGeometry(.22,.18,.8),this.mat(0x171b25));body.position.set(.28,-.22,-.55);g.add(body);let barrel=new THREE.Mesh(new THREE.CylinderGeometry(.045,.045,.55,12),this.mat(0x606b7d));barrel.rotation.x=Math.PI/2;barrel.position.set(.28,-.2,-.98);g.add(barrel);let grip=new THREE.Mesh(new THREE.BoxGeometry(.1,.3,.12),this.mat(0x202531));grip.position.set(.28,-.37,-.43);grip.rotation.x=-.25;g.add(grip);this.camera.add(g);this.scene.add(this.camera);this.weaponModel=g}
 enemy(x,z){let g=new THREE.Group();let body=new THREE.Mesh(new THREE.CapsuleGeometry(.34,.85,5,10),this.mat(0xb7364a));body.position.y=.85;body.castShadow=true;g.add(body);let head=new THREE.Mesh(new THREE.SphereGeometry(.27,16,12),this.mat(0xe2b7a7));head.position.y=1.55;g.add(head);let visor=new THREE.Mesh(new THREE.BoxGeometry(.35,.08,.04),this.mat(0x171c2a));visor.position.set(0,1.57,.24);g.add(visor);g.position.set(x,0,z);this.scene.add(g);return {g,hp:100,cd:0}}
 spawnBots(){for(const p of [[-18,-10],[15,-4],[28,15],[-25,28],[4,-28],[34,-30]])this.enemies.push(this.enemy(...p))}
 bind(){addEventListener('resize',()=>{this.camera.aspect=innerWidth/innerHeight;this.camera.updateProjectionMatrix();this.renderer.setSize(innerWidth,innerHeight)});document.addEventListener('keydown',e=>this.keys[e.code]=true);document.addEventListener('keyup',e=>this.keys[e.code]=false);this.renderer.domElement.addEventListener('click',()=>this.renderer.domElement.requestPointerLock());document.addEventListener('pointerlockchange',()=>this.lock=document.pointerLockElement===this.renderer.domElement);document.addEventListener('mousemove',e=>{if(!this.lock)return;this.yaw-=e.movementX*.0022;this.pitch-=e.movementY*.0018;this.pitch=Math.max(-1.45,Math.min(1.45,this.pitch));});addEventListener('mousedown',e=>{if(e.button===0&&this.lock)this.fire()});}
 fire(){if(this.ammo<=0)return;this.ammo--;this.ui.ammo(this.ammo);let dir=new THREE.Vector3(0,0,-1).applyQuaternion(this.camera.quaternion);let ray=new THREE.Raycaster(this.camera.position,dir,0,120);let hits=ray.intersectObjects(this.enemies.flatMap(e=>e.g.children),true);if(hits.length){let obj=hits[0].object;let e=this.enemies.find(x=>x.g.getObjectById(obj.id)||x.g.children.includes(obj));if(e){e.hp-=34;e.g.scale.y=.92;setTimeout(()=>e.g.scale.y=1,70);if(e.hp<=0){e.g.position.set((Math.random()-.5)*70,0,(Math.random()-.5)*70);e.hp=100}}}this.net.fire({x:this.camera.position.x,y:this.camera.position.y,z:this.camera.position.z},{x:dir.x,y:dir.y,z:dir.z});}
 netEvents(){this.net.on('player_joined',m=>this.addRemote(m.player));this.net.on('player_state',m=>this.updateRemote(m.player));this.net.on('player_left',m=>{let o=this.remote.get(m.id);if(o){this.scene.remove(o);this.remote.delete(m.id)}})}
 addRemote(p){if(p.id===this.net.id)return;let g=this.enemy(p.x,p.z);g.g.userData.remoteId=p.id;this.remote.set(p.id,g.g)}
 updateRemote(p){let g=this.remote.get(p.id);if(!g){this.addRemote(p);g=this.remote.get(p.id)}if(g){g.position.lerp(new THREE.Vector3(p.x,0,p.z),.45);g.rotation.y=p.yaw}}
 update(dt){let speed=this.keys.ShiftLeft?8:5.2;let v=new THREE.Vector3();if(this.keys.KeyW)v.z-=1;if(this.keys.KeyS)v.z+=1;if(this.keys.KeyA)v.x-=1;if(this.keys.KeyD)v.x+=1;if(v.lengthSq())v.normalize().multiplyScalar(speed*dt).applyAxisAngle(new THREE.Vector3(0,1,0),this.yaw);this.camera.position.add(v);this.camera.position.y=1.7;this.camera.rotation.set(this.pitch,this.yaw,0,'YXZ');if(this.keys.KeyR){this.ammo=25;this.ui.ammo(this.ammo);this.keys.KeyR=false}for(const e of this.enemies){let to=this.camera.position.clone().sub(e.g.position);to.y=0;if(to.length()<22)e.g.lookAt(this.camera.position.x,1,this.camera.position.z);e.cd-=dt;if(to.length()<18&&e.cd<=0){this.hp=Math.max(0,this.hp-7);this.ui.hp(this.hp);e.cd=1.1;if(this.hp<=0)this.respawn()}}this.net.state({x:this.camera.position.x,y:this.camera.position.y,z:this.camera.position.z,yaw:this.yaw,pitch:this.pitch,hp:this.hp,weapon:this.weapon})}
 respawn(){this.hp=100;this.camera.position.set(0,1.7,16);this.ui.hp(100)}
 loop(){requestAnimationFrame(()=>this.loop());let dt=Math.min(.05,this.clock.getDelta());this.update(dt);this.renderer.render(this.scene,this.camera)}
}
