import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';

const $=id=>document.getElementById(id);const lobby=$('lobby'),game=$('game'),boot=$('boot');
const weapons=[['NX-9','RIFLE','25 / 100','balanced rifle'],['VX-77','CARBINE','30 / 120','fast handling'],['ARC-12','SHOTGUN','8 / 48','close quarters'],['SMG-X','SMG','36 / 144','high fire rate']];
const agents=[['KAIRO','VANGUARD','Frontline operator'],['MIRA','SPECTER','Recon and mobility'],['REI','WARDEN','Defensive specialist']];
const maps=[['KYOTO NIGHT','SHADOWS OF KYOTO','Torii lanes · gardens · neon market'],['NEON HARBOR','PACIFIC FRONT','Industrial docks · rain · containers'],['RED TEMPLE','MOUNTAIN DISTRICT','Shrines · cliffs · bamboo']];
$('weaponGrid').innerHTML=weapons.map(w=>`<article class="weapon-card"><h3>${w[0]}</h3><p>${w[1]} · ${w[2]}<br>${w[3]}</p><div class="card-art"></div></article>`).join('');
$('agentGrid').innerHTML=agents.map(a=>`<article class="agent-card"><h3>${a[0]}</h3><p>${a[1]}<br>${a[2]}</p><div class="agent-art"></div></article>`).join('');
$('mapGrid').innerHTML=maps.map(m=>`<article class="map-card"><h3>${m[0]}</h3><p>${m[1]}<br>${m[2]}</p><div class="map-art"></div></article>`).join('');
let selectedWeapon='NX-9',selectedMode='ranked';
function tabs(){document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));$('panel-'+b.dataset.panel).classList.add('active')})}
tabs();document.querySelectorAll('.mode').forEach(b=>b.onclick=()=>{document.querySelectorAll('.mode').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');selectedMode=b.dataset.mode});
setTimeout(()=>{boot.classList.add('hidden');$('app').classList.remove('hidden')},900);

let scene,camera,renderer,clock,weapon,flash,gameRunning=false,mouseLocked=false;let hp=100,ammo=25,score=0,round=1;const keys={},bots=[],tracers=[],obstacles=[];
const player={pos:new THREE.Vector3(0,1.7,18),vel:new THREE.Vector3(),yaw:Math.PI,pitch:0,grounded:true};
const gunStats={ 'NX-9':{mag:25,rate:105,damage:34,spread:.009,pellets:1},'VX-77':{mag:30,rate:135,damage:27,spread:.013,pellets:1},'ARC-12':{mag:8,rate:70,damage:18,spread:.09,pellets:7},'SMG-X':{mag:36,rate:850,damage:17,spread:.026,pellets:1} };
let lastShot=0,reloading=false;
function mat(c,rough=.65,metal=0){return new THREE.MeshStandardMaterial({color:c,roughness:rough,metalness:metal})}
function box(x,y,z,c,pos,rot=0){const m=new THREE.Mesh(new THREE.BoxGeometry(x,y,z),mat(c));m.position.copy(pos);m.rotation.y=rot;m.castShadow=true;m.receiveShadow=true;scene.add(m);obstacles.push(m);return m}
function cyl(r,h,c,pos,seg=12){const m=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,seg),mat(c));m.position.copy(pos);m.castShadow=true;m.receiveShadow=true;scene.add(m);return m}
function createTorii(x,z,s=1){const red=mat(0x9b252b);[-2.4,2.4].forEach(dx=>{const p=new THREE.Mesh(new THREE.CylinderGeometry(.22,.25,5.2,12),red);p.position.set(x+dx*s,2.6,z);p.castShadow=true;scene.add(p)});const bar=new THREE.Mesh(new THREE.BoxGeometry(6.2*s,.35,.42),red);bar.position.set(x,5,z);bar.castShadow=true;scene.add(bar);const bar2=bar.clone();bar2.scale.y=.72;bar2.position.y=4.35;scene.add(bar2)}
function createTree(x,z,s=1){const trunk=cyl(.22,2.3,0x553a29,new THREE.Vector3(x,1.15,z));const crown=new THREE.Mesh(new THREE.IcosahedronGeometry(1.35*s,1),mat(0x183d34));crown.position.set(x,2.7,z);crown.castShadow=true;scene.add(crown);return trunk}
function createMap(){const floor=new THREE.Mesh(new THREE.PlaneGeometry(90,90),new THREE.MeshStandardMaterial({color:0x182224,roughness:.9}));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;scene.add(floor);for(let i=-40;i<=40;i+=5){const line=new THREE.Mesh(new THREE.BoxGeometry(.025,.01,90),new THREE.MeshBasicMaterial({color:0x304144,transparent:true,opacity:.16}));line.position.set(i,.01,0);scene.add(line);const line2=line.clone();line2.rotation.y=Math.PI/2;scene.add(line2)}
 box(90,8,1,0x101719,new THREE.Vector3(0,4,-45));box(90,8,1,0x101719,new THREE.Vector3(0,4,45));box(1,8,90,0x101719,new THREE.Vector3(-45,4,0));box(1,8,90,0x101719,new THREE.Vector3(45,4,0));
 createTorii(0,-30,1.2);createTorii(-25,5,.75);createTorii(25,5,.75);for(let x=-36;x<=36;x+=9){createTree(x,-38,.9);createTree(x,38,.7)}
 // shrine
 box(12,.35,8,0x302824,new THREE.Vector3(0,.2,-35));box(8,4,5,0x211d1c,new THREE.Vector3(0,2,-35));for(let x=-5;x<=5;x+=2.5)cyl(.18,4,0x7e2529,new THREE.Vector3(x,2,-31));
 // market structures and tactical cover
 for(const p of [[-14,0,8],[14,0,8],[-14,0,-8],[14,0,-8],[0,0,5],[0,0,-5]]){box(7,3.2,1.1,0x263538,new THREE.Vector3(p[0],1.6,p[2]));box(1.1,3.2,7,0x263538,new THREE.Vector3(p[0]+3,1.6,p[2]+3))}
 for(let x=-30;x<=30;x+=10){box(2,1.2,2,0x6a4931,new THREE.Vector3(x,.6,17));box(2,1.2,2,0x6a4931,new THREE.Vector3(x,.6,-17))}
 for(let i=0;i<20;i++){const a=new THREE.Mesh(new THREE.BoxGeometry(.35,.05,1.2),new THREE.MeshBasicMaterial({color:0xffa15b}));a.position.set(-38+Math.random()*76,.04,-40+Math.random()*80);a.rotation.y=Math.random()*Math.PI;scene.add(a)} }
function createWeapon(){const g=new THREE.Group();const dark=mat(0x20262a,.3,.75),black=mat(0x090b0c,.25,.85),accent=mat(0x7d8e92,.3,.8);const body=new THREE.Mesh(new THREE.BoxGeometry(.18,.2,.8),dark);body.position.set(.34,-.31,-.78);body.rotation.x=-.04;g.add(body);const barrel=new THREE.Mesh(new THREE.CylinderGeometry(.045,.05,.55,12),black);barrel.rotation.x=Math.PI/2;barrel.position.set(.34,-.3,-1.43);g.add(barrel);const grip=new THREE.Mesh(new THREE.BoxGeometry(.12,.38,.16),black);grip.position.set(.34,-.55,-.55);grip.rotation.x=-.2;g.add(grip);const sight=new THREE.Mesh(new THREE.BoxGeometry(.05,.08,.2),accent);sight.position.set(.34,-.18,-.78);g.add(sight);g.position.set(.04,0,0);camera.add(g);return g}
function createEnemy(pos,name){const root=new THREE.Group();root.position.copy(pos);const body=mat(0x18242a),armor=mat(0x34454b,.35,.35),skin=mat(0xb87860),visor=mat(0x70d0d0,.18,.5);const torso=new THREE.Mesh(new THREE.CapsuleGeometry(.48,.9,6,10),body);torso.position.y=1.15;torso.castShadow=true;root.add(torso);const chest=new THREE.Mesh(new THREE.BoxGeometry(.8,.62,.3),armor);chest.position.set(0,1.35,.12);chest.castShadow=true;root.add(chest);const head=new THREE.Mesh(new THREE.SphereGeometry(.34,16,12),skin);head.position.y=2.05;head.castShadow=true;root.add(head);const helmet=new THREE.Mesh(new THREE.SphereGeometry(.38,16,10,0,Math.PI*2,0,Math.PI/2),armor);helmet.position.y=2.12;root.add(helmet);const face=new THREE.Mesh(new THREE.BoxGeometry(.38,.12,.06),visor);face.position.set(0,2.03,.32);root.add(face);for(const side of [-1,1]){const arm=new THREE.Mesh(new THREE.CapsuleGeometry(.14,.7,5,8),armor);arm.position.set(side*.58,1.25,0);arm.rotation.z=side*.25;root.add(arm);const leg=new THREE.Mesh(new THREE.CapsuleGeometry(.16,.8,5,8),armor);leg.position.set(side*.22,.45,0);root.add(leg)}const gun=new THREE.Mesh(new THREE.BoxGeometry(.12,.12,.7),black);gun.position.set(.55,1.05,-.35);gun.rotation.x=-.1;root.add(gun);scene.add(root);const b={root,hp:100,name,alive:true,dir:new THREE.Vector3(),next:performance.now()+Math.random()*2000};bots.push(b);return b}
function init(){scene=new THREE.Scene();scene.background=new THREE.Color(0x071014);scene.fog=new THREE.FogExp2(0x071014,.012);camera=new THREE.PerspectiveCamera(72,innerWidth/innerHeight,.05,150);camera.position.copy(player.pos);renderer=new THREE.WebGLRenderer({canvas:$('world'),antialias:true,powerPreference:'high-performance'});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;clock=new THREE.Clock();const hemi=new THREE.HemisphereLight(0x9fc4d0,0x08090b,1.4);scene.add(hemi);const moon=new THREE.DirectionalLight(0xd7e6ff,2.3);moon.position.set(-20,35,-25);moon.castShadow=true;moon.shadow.mapSize.set(2048,2048);scene.add(moon);const warm=new THREE.PointLight(0xff743f,30,24);warm.position.set(0,5,-30);scene.add(warm);createMap();weapon=createWeapon();flash=new THREE.PointLight(0xffb36a,0,4);camera.add(flash);scene.add(camera);for(const p of [[-22,1,-12],[22,1,-10],[-20,1,15],[20,1,16],[-5,1,-20],[8,1,25]])createEnemy(new THREE.Vector3(p[0],0,p[2]),'HOSTILE');animate()}
function fire(){if(!gameRunning||reloading)return;const s=gunStats[selectedWeapon];const now=performance.now();if(now-lastShot<60000/s.rate)return;if(ammo<=0){reload();return}lastShot=now;ammo--;updateHUD();flash.intensity=8;setTimeout(()=>flash.intensity=0,45);for(let k=0;k<s.pellets;k++){const ray=new THREE.Raycaster();const spread=s.spread;const dir=new THREE.Vector3((Math.random()-.5)*spread,(Math.random()-.5)*spread,-1).applyQuaternion(camera.quaternion).normalize();ray.set(camera.position,dir);const targets=[];bots.forEach(b=>{if(b.alive)b.root.traverse(o=>{if(o.isMesh)targets.push(o)})});const hit=ray.intersectObjects(targets,false)[0];if(hit){let b=bots.find(x=>{let ok=false;x.root.traverse(o=>{if(o===hit.object)ok=true});return ok});if(b){b.hp-=s.damage;if(b.hp<=0)killBot(b);showHit()}}const end=camera.position.clone().add(dir.multiplyScalar(70));const geom=new THREE.BufferGeometry().setFromPoints([camera.position.clone(),end]);const beam=new THREE.Line(geom,new THREE.LineBasicMaterial({color:0xffd39a,transparent:true,opacity:.65}));scene.add(beam);tracers.push({beam,t:performance.now()})}}
function showHit(){const h=$('hitmarker');h.style.opacity=1;setTimeout(()=>h.style.opacity=0,90)}function killBot(b){b.alive=false;score++;$('blueScore').textContent=score;b.root.rotation.z=-.9;b.root.position.y=.35;feed('HOSTILE NEUTRALIZED');setTimeout(()=>respawnBot(b),1800)}function respawnBot(b){b.hp=100;b.alive=true;b.root.rotation.z=0;b.root.position.set((Math.random()-.5)*60,0,(Math.random()-.5)*60)}function reload(){if(reloading||ammo===gunStats[selectedWeapon].mag)return;reloading=true;setTimeout(()=>{ammo=gunStats[selectedWeapon].mag;reloading=false;updateHUD()},900)}function feed(t){const f=$('killFeed');const e=document.createElement('div');e.textContent=t;f.appendChild(e);setTimeout(()=>e.remove(),2500)}function updateHUD(){$('ammo').textContent=ammo;$('weaponHud').textContent=selectedWeapon;$('weaponName').textContent=selectedWeapon;$('hp').textContent=Math.max(0,Math.round(hp));$('hpBar').style.width=Math.max(0,hp)+'%'}
function move(dt){const speed=keys.ShiftLeft||keys.ShiftRight?8.5:5.5;const forward=new THREE.Vector3(Math.sin(player.yaw),0,Math.cos(player.yaw));const right=new THREE.Vector3(Math.cos(player.yaw),0,-Math.sin(player.yaw));let v=new THREE.Vector3();if(keys.KeyW)v.add(forward);if(keys.KeyS)v.sub(forward);if(keys.KeyD)v.add(right);if(keys.KeyA)v.sub(right);if(v.lengthSq())v.normalize().multiplyScalar(speed*dt);player.pos.add(v);player.pos.x=THREE.MathUtils.clamp(player.pos.x,-41,41);player.pos.z=THREE.MathUtils.clamp(player.pos.z,-41,41);camera.position.copy(player.pos);camera.rotation.set(player.pitch,player.yaw,0,'YXZ');weapon.rotation.z=Math.sin(performance.now()*.012)*.006;weapon.position.y=Math.sin(performance.now()*.01)*.008}
function ai(){for(const b of bots){if(!b.alive)continue;const d=player.pos.clone().sub(b.root.position);const dist=d.length();if(dist>5){d.y=0;d.normalize();b.root.position.addScaledVector(d,.018);b.root.lookAt(player.pos.x,b.root.position.y,player.pos.z)}else if(performance.now()>b.next){b.next=performance.now()+900+Math.random()*800;if(Math.random()<.35){hp-=7;updateHUD();$('damageFlash').style.opacity=.8;setTimeout(()=>$('damageFlash').style.opacity=0,80);if(hp<=0)die()}}}}
function die(){hp=100;player.pos.set(0,1.7,18);round++;$('roundNo').textContent=String(round).padStart(2,'0');feed('RESPAWNING')}
function animate(){requestAnimationFrame(animate);if(!renderer)return;const dt=Math.min(clock.getDelta(),.05);if(gameRunning){move(dt);ai();tracers.splice(0,tracers.length-12).forEach(x=>{scene.remove(x.beam)});renderer.render(scene,camera)}}
function start(){lobby.classList.add('hidden');game.classList.remove('hidden');gameRunning=true;if(!scene)init();$('buyMenu').classList.remove('hidden');setTimeout(()=>$('buyMenu').classList.add('hidden'),1800);document.body.requestPointerLock?.();}
$('playBtn').onclick=start;$('resume').onclick=()=>{$('pause').classList.add('hidden');document.body.requestPointerLock?.()};$('leave').onclick=()=>{gameRunning=false;game.classList.add('hidden');lobby.classList.remove('hidden');document.exitPointerLock?.()};$('closeBuy').onclick=()=>{$('buyMenu').classList.add('hidden');document.body.requestPointerLock?.()};
addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='KeyR')reload();if(e.code==='Escape'&&gameRunning)$('pause').classList.toggle('hidden');if(e.code==='Digit1')selectedWeapon='NX-9';if(e.code==='Digit2')selectedWeapon='VX-77';if(e.code==='Digit3')selectedWeapon='ARC-12';if(e.code==='Digit4')selectedWeapon='SMG-X';updateHUD()});addEventListener('keyup',e=>keys[e.code]=false);addEventListener('mousedown',e=>{if(e.button===0){document.body.requestPointerLock?.();fire()}});addEventListener('mousemove',e=>{if(document.pointerLockElement!==document.body||!gameRunning)return;player.yaw-=e.movementX*.0022;player.pitch-=e.movementY*.0022;player.pitch=THREE.MathUtils.clamp(player.pitch,-1.35,1.35)});addEventListener('resize',()=>{if(renderer){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)}});updateHUD();
