import http from 'node:http';
import {readFile} from 'node:fs/promises';
import {extname,join,normalize} from 'node:path';
import crypto from 'node:crypto';
import {WebSocketServer} from 'ws';
const PORT=process.env.PORT||3000, ROOT=process.cwd();
const players=new Map(), rooms=new Map([['haven-x',new Set()]]);
const types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.png':'image/png','.jpg':'image/jpeg','.svg':'image/svg+xml'};
const server=http.createServer(async(req,res)=>{try{let path=normalize(req.url.split('?')[0]);if(path==='/'||path==='')path='/index.html';if(path.includes('..'))throw 404;const data=await readFile(join(ROOT,path));res.writeHead(200,{'content-type':types[extname(path)]||'application/octet-stream'});res.end(data)}catch{res.writeHead(404);res.end('Not found')}});
const wss=new WebSocketServer({server});
const send=(ws,type,data={})=>ws.readyState===1&&ws.send(JSON.stringify({type,...data}));
const broadcast=(room,type,data,except)=>{for(const id of room){const p=players.get(id);if(p&&p.ws!==except)send(p.ws,type,data)}};
const snapshot=room=>[...room].map(id=>{const p=players.get(id);return{id:p.id,name:p.name,x:p.x,y:p.y,z:p.z,yaw:p.yaw,pitch:p.pitch,hp:p.hp,weapon:p.weapon,team:p.team}});
wss.on('connection',ws=>{const id=crypto.randomUUID();const p={id,ws,name:'Player',x:0,y:1.7,z:16,yaw:0,pitch:0,hp:100,weapon:'NX-9',team:'attackers',room:'haven-x'};players.set(id,p);rooms.get(p.room).add(id);send(ws,'welcome',{id,room:p.room,players:snapshot(rooms.get(p.room))});broadcast(rooms.get(p.room),'player_joined',{player:p},ws);
ws.on('message',raw=>{let m;try{m=JSON.parse(raw)}catch{return}if(m.type==='hello')p.name=String(m.name||'Player').slice(0,18);if(m.type==='state'){p.x=Number(m.x)||0;p.y=Number(m.y)||1.7;p.z=Number(m.z)||0;p.yaw=Number(m.yaw)||0;p.pitch=Number(m.pitch)||0;p.hp=Math.max(0,Math.min(100,Number(m.hp)||0));p.weapon=String(m.weapon||p.weapon).slice(0,20);broadcast(rooms.get(p.room),'player_state',{player:p},ws)}if(m.type==='fire')broadcast(rooms.get(p.room),'remote_fire',{id:p.id,origin:m.origin||{},direction:m.direction||{},weapon:p.weapon},ws);if(m.type==='chat')broadcast(rooms.get(p.room),'chat',{name:p.name,text:String(m.text||'').slice(0,160)});});
ws.on('close',()=>{players.delete(id);rooms.get(p.room)?.delete(id);broadcast(rooms.get(p.room),'player_left',{id})})});server.listen(PORT,()=>console.log(`Nexstrike online on ${PORT}`));
